function [endEffectorMm, pointsMm] = manipulator_fk(qDeg, p)
%MANIPULATOR_FK Forward kinematics matching manipulator_ik conventions.

arguments
    qDeg (1,6) double
    p (1,1) struct
end

q = deg2rad(qDeg);
q1 = q(1);
q2 = q(2);
q23 = q(2) + q(3);
q234 = q(2) + q(3) + q(4);

radial = [0, ...
          0, ...
          p.link1Mm*cos(q2), ...
          p.link1Mm*cos(q2) + p.link2Mm*cos(q23), ...
          p.link1Mm*cos(q2) + p.link2Mm*cos(q23) + ...
              p.toolOffsetMm*cos(q234)];
z = [0, ...
     p.baseHeightMm, ...
     p.baseHeightMm + p.link1Mm*sin(q2), ...
     p.baseHeightMm + p.link1Mm*sin(q2) + p.link2Mm*sin(q23), ...
     p.baseHeightMm + p.link1Mm*sin(q2) + p.link2Mm*sin(q23) + ...
         p.toolOffsetMm*sin(q234)];

pointsMm = [radial(:)*cos(q1), radial(:)*sin(q1), z(:)];
endEffectorMm = pointsMm(end, :);
end
